In [79]:
import numpy as np
import pandas as pd

In [80]:
rooms = pd.read_csv('roomdataset.csv')

In [81]:
rooms.head(1)

_id        lng        lat  price  \
0  649704d7cd2d701f93cfbbc5  85.325322  27.740097  30000   

                                               title  \
0  Furnished flat for rent is available at Basund...   

                                         description  \
0  Furnished flat for rent is available at Basund...   

                                         address                 place  \
0  Ayurveda Health Home, Dhapasi, Bagmati, Nepal  Ayurveda Health Home   

                               amenities[0]  \
0  Dishwasher,Parking,Private Bathroom,Yard   

                                   img_collection[0]  ... img_collection[6]  \
0  http://localhost:8000/uploads/2023-06-24T14-59...  ...               NaN   

  img_collection[7]                       uid             uName  \
0               NaN  646df4504e002a5def537e26  Sahash Chaduhary   

             uEmail      uPhone  \
0  sahash@gmail.com  9831279215   

                                              uPhoto  \
0  2023-05-24T11-26-07.265Z-00100sPORTRAIT_00100_...   

                  createdAt                 updatedAt __v  
0  2023-06-24T14:59:35.509Z  2023-06-24T14:59:35.509Z   0  

[1 rows x 25 columns]

In [82]:
print(rooms.columns)

Index(['_id', 'lng', 'lat', 'price', 'title', 'description', 'address',
       'place', 'amenities[0]', 'img_collection[0]', 'img_collection[1]',
       'img_collection[2]', 'img_collection[3]', 'img_collection[4]',
       'img_collection[5]', 'img_collection[6]', 'img_collection[7]', 'uid',
       'uName', 'uEmail', 'uPhone', 'uPhoto', 'createdAt', 'updatedAt', '__v'],
      dtype='object')


In [83]:
rooms = rooms.loc[:, ['_id', 'title', 'description', 'address', 'lng', 'lat', 'price', 'amenities[0]']]

In [84]:
rooms.head()

_id  \
0  649704d7cd2d701f93cfbbc5   
1  6497061ccd2d701f93cfbbcf   
2  64970670cd2d701f93cfbbd7   
3  64970739cd2d701f93cfbbe8   
4  64970881cd2d701f93cfbbf0   

                                               title  \
0  Furnished flat for rent is available at Basund...   
1                       2 rooms for rent in Om bahal   
2                            Flat for rent at Grande   
3                   Flat for rent at golfutar hepali   
4                             Flat for rent at Lubhu   

                                         description  \
0  Furnished flat for rent is available at Basund...   
1  flat for rent in Om bahal Balcony available 3r...   
2  2 bedroom,kitchen,living with bathroom 1st flo...   
3  3 room,kitchen with bathroom Big Parking Space...   
4  2 Bed Room 1 Living Room 1 Kitchen 1 Bathroom ...   

                                             address        lng        lat  \
0      Ayurveda Health Home, Dhapasi, Bagmati, Nepal  85.325322  27.740097   
1                 Dhukuti, Kathmandu, Bagmati, Nepal  85.309230  27.698511   
2           Grande Hospital, Dhapasi, Bagmati, Nepal  85.326453  27.751612   
3  National Institute of Neurological and Allied ...  85.348257  27.748791   
4             Lubhu, Lubhu, Lalitpur, Bagmati, Nepal  85.372956  27.644263   

   price                              amenities[0]  
0  30000  Dishwasher,Parking,Private Bathroom,Yard  
1  15000                        Dishwasher,Parking  
2  17000       Dishwasher,Parking,Private Bathroom  
3  20000  Dishwasher,Parking,Private Bathroom,Yard  
4  14000       Dishwasher,Parking,Private Bathroom

In [85]:
print(rooms.columns)

Index(['_id', 'title', 'description', 'address', 'lng', 'lat', 'price',
       'amenities[0]'],
      dtype='object')


In [86]:
rooms.isnull().sum()

_id              0
title            0
description      0
address          0
lng              0
lat              0
price            0
amenities[0]    11
dtype: int64

In [87]:
rooms.duplicated().sum()

0

In [88]:
rooms.head(1)['amenities[0]'].values

array(['Dishwasher,Parking,Private Bathroom,Yard'], dtype=object)

In [89]:
rooms['description'] = rooms['description'].apply(lambda x:x.split())

In [90]:
rooms['title'] = rooms['title'].apply(lambda x:x.split())

In [91]:
rooms['address'] = rooms['address'].apply(lambda x:x.split())

In [92]:
rooms['title'] = rooms['title'].apply(lambda x:[i.replace(" ","") for i in x])
rooms['description'] = rooms['description'].apply(lambda x:[i.replace(" ","") for i in x])
rooms['address'] = rooms['address'].apply(lambda x:[i.replace(" ","") for i in x])

In [93]:
rooms.head()

_id  \
0  649704d7cd2d701f93cfbbc5   
1  6497061ccd2d701f93cfbbcf   
2  64970670cd2d701f93cfbbd7   
3  64970739cd2d701f93cfbbe8   
4  64970881cd2d701f93cfbbf0   

                                               title  \
0  [Furnished, flat, for, rent, is, available, at...   
1               [2, rooms, for, rent, in, Om, bahal]   
2                      [Flat, for, rent, at, Grande]   
3            [Flat, for, rent, at, golfutar, hepali]   
4                       [Flat, for, rent, at, Lubhu]   

                                         description  \
0  [Furnished, flat, for, rent, is, available, at...   
1  [flat, for, rent, in, Om, bahal, Balcony, avai...   
2  [2, bedroom,kitchen,living, with, bathroom, 1s...   
3  [3, room,kitchen, with, bathroom, Big, Parking...   
4  [2, Bed, Room, 1, Living, Room, 1, Kitchen, 1,...   

                                             address        lng        lat  \
0  [Ayurveda, Health, Home,, Dhapasi,, Bagmati,, ...  85.325322  27.740097   
1            [Dhukuti,, Kathmandu,, Bagmati,, Nepal]  85.309230  27.698511   
2     [Grande, Hospital,, Dhapasi,, Bagmati,, Nepal]  85.326453  27.751612   
3  [National, Institute, of, Neurological, and, A...  85.348257  27.748791   
4       [Lubhu,, Lubhu,, Lalitpur,, Bagmati,, Nepal]  85.372956  27.644263   

   price                              amenities[0]  
0  30000  Dishwasher,Parking,Private Bathroom,Yard  
1  15000                        Dishwasher,Parking  
2  17000       Dishwasher,Parking,Private Bathroom  
3  20000  Dishwasher,Parking,Private Bathroom,Yard  
4  14000       Dishwasher,Parking,Private Bathroom

In [94]:
rooms['tags'] = rooms['title'].astype(str) + rooms['description'].astype(str) + rooms['address'].astype(str) + rooms['amenities[0]'].astype(str)

In [95]:
rooms.head()

_id  \
0  649704d7cd2d701f93cfbbc5   
1  6497061ccd2d701f93cfbbcf   
2  64970670cd2d701f93cfbbd7   
3  64970739cd2d701f93cfbbe8   
4  64970881cd2d701f93cfbbf0   

                                               title  \
0  [Furnished, flat, for, rent, is, available, at...   
1               [2, rooms, for, rent, in, Om, bahal]   
2                      [Flat, for, rent, at, Grande]   
3            [Flat, for, rent, at, golfutar, hepali]   
4                       [Flat, for, rent, at, Lubhu]   

                                         description  \
0  [Furnished, flat, for, rent, is, available, at...   
1  [flat, for, rent, in, Om, bahal, Balcony, avai...   
2  [2, bedroom,kitchen,living, with, bathroom, 1s...   
3  [3, room,kitchen, with, bathroom, Big, Parking...   
4  [2, Bed, Room, 1, Living, Room, 1, Kitchen, 1,...   

                                             address        lng        lat  \
0  [Ayurveda, Health, Home,, Dhapasi,, Bagmati,, ...  85.325322  27.740097   
1            [Dhukuti,, Kathmandu,, Bagmati,, Nepal]  85.309230  27.698511   
2     [Grande, Hospital,, Dhapasi,, Bagmati,, Nepal]  85.326453  27.751612   
3  [National, Institute, of, Neurological, and, A...  85.348257  27.748791   
4       [Lubhu,, Lubhu,, Lalitpur,, Bagmati,, Nepal]  85.372956  27.644263   

   price                              amenities[0]  \
0  30000  Dishwasher,Parking,Private Bathroom,Yard   
1  15000                        Dishwasher,Parking   
2  17000       Dishwasher,Parking,Private Bathroom   
3  20000  Dishwasher,Parking,Private Bathroom,Yard   
4  14000       Dishwasher,Parking,Private Bathroom   

                                                tags  
0  ['Furnished', 'flat', 'for', 'rent', 'is', 'av...  
1  ['2', 'rooms', 'for', 'rent', 'in', 'Om', 'bah...  
2  ['Flat', 'for', 'rent', 'at', 'Grande']['2', '...  
3  ['Flat', 'for', 'rent', 'at', 'golfutar', 'hep...  
4  ['Flat', 'for', 'rent', 'at', 'Lubhu']['2', 'B...

In [96]:
rooms['tags'][0]

"['Furnished', 'flat', 'for', 'rent', 'is', 'available', 'at', 'Basundhara', 'Kathmandu']['Furnished', 'flat', 'for', 'rent', 'is', 'available', 'at', 'Basundhara', 'Kathmandu.', 'This', 'house', 'has', 'two', 'big', 'bedrooms,', 'living,', 'kitchen', 'and', 'bathroom.', 'It', 'is', 'located', 'just', '200', 'meters', 'inside', 'from', 'main', 'Basundhara', 'chowk.']['Ayurveda', 'Health', 'Home,', 'Dhapasi,', 'Bagmati,', 'Nepal']Dishwasher,Parking,Private Bathroom,Yard"

In [97]:
rooms['tags'] = rooms['tags'].apply(lambda x: " ".join(x.replace("', '", " ").replace("['", "").replace("']", "").split()))

In [98]:
rooms['tags'][0]

'Furnished flat for rent is available at Basundhara KathmanduFurnished flat for rent is available at Basundhara Kathmandu. This house has two big bedrooms, living, kitchen and bathroom. It is located just 200 meters inside from main Basundhara chowk.Ayurveda Health Home, Dhapasi, Bagmati, NepalDishwasher,Parking,Private Bathroom,Yard'

In [99]:
rooms['tags'] = rooms['tags'].apply(lambda x: x.replace("'", "").replace('"', ''))

In [100]:
rooms['tags'][0]

'Furnished flat for rent is available at Basundhara KathmanduFurnished flat for rent is available at Basundhara Kathmandu. This house has two big bedrooms, living, kitchen and bathroom. It is located just 200 meters inside from main Basundhara chowk.Ayurveda Health Home, Dhapasi, Bagmati, NepalDishwasher,Parking,Private Bathroom,Yard'

In [101]:
new_df = rooms[['_id','price','lng','lat','tags']]

In [102]:
new_df

_id  price        lng        lat  \
0   649704d7cd2d701f93cfbbc5  30000  85.325322  27.740097   
1   6497061ccd2d701f93cfbbcf  15000  85.309230  27.698511   
2   64970670cd2d701f93cfbbd7  17000  85.326453  27.751612   
3   64970739cd2d701f93cfbbe8  20000  85.348257  27.748791   
4   64970881cd2d701f93cfbbf0  14000  85.372956  27.644263   
..                       ...    ...        ...        ...   
95  649813de20eff54bd37dcd27   8500  85.345157  27.675435   
96  6498143b20eff54bd37dcd3d  10000  85.348173  27.699638   
97  649814ca20eff54bd37dcd45  20000  85.309409  27.678250   
98  6498153020eff54bd37dcd4d  20000  85.309862  27.676413   
99  6498159920eff54bd37dcd5f   5000  85.368305  27.735556   

                                                 tags  
0   Furnished flat for rent is available at Basund...  
1   2 rooms for rent in Om bahalflat for rent in O...  
2   Flat for rent at Grande2 bedroom,kitchen,livin...  
3   Flat for rent at golfutar hepali3 room,kitchen...  
4   Flat for rent at Lubhu2 Bed Room 1 Living Room...  
..                                                ...  
95  1 Big Room And Small Room Koteshwor Bhatbhatan...  
96  Big room 2nd flr 10kIn minbhavan, new baneswor...  
97  Room at jhamiskhelthis room is located at jham...  
98  Two Sitter Roomthis room is For hostel student...  
99  Romm on Rent (Two Room)Two room on rent on Kap...  

[100 rows x 5 columns]

In [103]:
new_df['tags'][0]

'Furnished flat for rent is available at Basundhara KathmanduFurnished flat for rent is available at Basundhara Kathmandu. This house has two big bedrooms, living, kitchen and bathroom. It is located just 200 meters inside from main Basundhara chowk.Ayurveda Health Home, Dhapasi, Bagmati, NepalDishwasher,Parking,Private Bathroom,Yard'

In [104]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\empsw\AppData\Local\Temp\ipykernel_13108\3214958533.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())


In [105]:
new_df['tags'][0]

'furnished flat for rent is available at basundhara kathmandufurnished flat for rent is available at basundhara kathmandu. this house has two big bedrooms, living, kitchen and bathroom. it is located just 200 meters inside from main basundhara chowk.ayurveda health home, dhapasi, bagmati, nepaldishwasher,parking,private bathroom,yard'

In [106]:
!pip install nltk

In [107]:
import nltk

In [108]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [109]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [110]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\empsw\AppData\Local\Temp\ipykernel_13108\3213734980.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)


In [111]:
new_df['tags'][0]

'furnish flat for rent is avail at basundhara kathmandufurnish flat for rent is avail at basundhara kathmandu. thi hous ha two big bedrooms, living, kitchen and bathroom. it is locat just 200 meter insid from main basundhara chowk.ayurveda health home, dhapasi, bagmati, nepaldishwasher,parking,priv bathroom,yard'

In [112]:
ps.stem('loved')

'love'

In [113]:
ps.stem('loving')

'love'

In [114]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000,stop_words='english')

In [115]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [116]:
vectors[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [117]:
cv.get_feature_names()

C:\Users\empsw\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['00',
 '000',
 '000da',
 '10',
 '100',
 '1000',
 '10kglobal',
 '10kin',
 '1150',
 '12',
 '1200',
 '12000',
 '12x15',
 '13',
 '1369',
 '15',
 '150',
 '15000',
 '15x17',
 '16',
 '17000grand',
 '1790',
 '18',
 '1rst',
 '1st',
 '1tallogau',
 '20',
 '200',
 '2000',
 '20000',
 '200m',
 '24',
 '24hr',
 '24hrpepsi',
 '25',
 '2500',
 '25000',
 '2bhk',
 '2flat',
 '2nd',
 '2room3',
 '300',
 '3124',
 '32',
 '3300',
 '3500',
 '35000',
 '3bhk',
 '3rd',
 '4000',
 '40000',
 '45',
 '4bhk',
 '50',
 '500',
 '5000',
 '50000sahe',
 '5476',
 '5500',
 '6000',
 '70',
 '700',
 '7000',
 '7000maitidevi',
 '795',
 '8500',
 '9000prashant',
 '909',
 '945',
 '9th',
 'ac',
 'accesible',
 'access',
 'accesslahana',
 'accommod',
 'accord',
 'ace',
 'adarsha',
 'adequ',
 'air',
 'airport',
 'alli',
 'allow',
 'anamnagar',
 'anfa',
 'angl',
 'ani',
 'apart',
 'appart',
 'approx',
 'approxim',
 'area',
 'ashram',
 'attach',
 'attract',
 'author',
 'avail',
 'available',
 'availableadarsha',
 'availableanfa',
 'availablea

In [118]:
from sklearn.metrics.pairwise import cosine_similarity

In [119]:
similaritytags = cosine_similarity(vectors)

In [120]:
similaritytags

array([[1.        , 0.27500955, 0.43876345, ..., 0.12002401, 0.12002401,
        0.20438501],
       [0.27500955, 1.        , 0.34188173, ..., 0.24939187, 0.09352195,
        0.40951418],
       [0.43876345, 0.34188173, 1.        , ..., 0.22381413, 0.14920942,
        0.2903816 ],
       ...,
       [0.12002401, 0.24939187, 0.22381413, ..., 1.        , 0.55102041,
        0.32766551],
       [0.12002401, 0.09352195, 0.14920942, ..., 0.55102041, 1.        ,
        0.14893887],
       [0.20438501, 0.40951418, 0.2903816 , ..., 0.32766551, 0.14893887,
        1.        ]])

In [121]:
similaritytags[0]

array([1.        , 0.27500955, 0.43876345, 0.38423369, 0.35486043,
       0.2300895 , 0.26948403, 0.418719  , 0.38437328, 0.32839479,
       0.38348249, 0.38423369, 0.3363364 , 0.39674602, 0.19274777,
       0.21170245, 0.27461752, 0.12849851, 0.27258651, 0.52071918,
       0.11651035, 0.153393  , 0.28924061, 0.10502101, 0.17327582,
       0.26948403, 0.31203058, 0.19802951, 0.33665016, 0.22422426,
       0.27258651, 0.21558722, 0.17368337, 0.17193776, 0.17503501,
       0.25743836, 0.24545785, 0.28088828, 0.24111312, 0.51399405,
       0.17778266, 0.30267507, 0.2655274 , 0.19211684, 0.27624555,
       0.19802951, 0.22961557, 0.28005602, 0.16803361, 0.23529412,
       0.17494961, 0.24987097, 0.23816526, 0.08759357, 0.22636658,
       0.22715543, 0.14291549, 0.35239609, 0.10984701, 0.17327582,
       0.17327582, 0.21004201, 0.17912443, 0.14297629, 0.25699703,
       0.46114013, 0.40611056, 0.37162806, 0.35645312, 0.54010803,
       0.17604841, 0.49507377, 0.33612278, 0.38423369, 0.24004

In [122]:
from sklearn.preprocessing import MinMaxScaler

In [123]:
price_values = new_df['price']

In [124]:
# Initialize the MinMaxScaler
scaler = MinMaxScaler()

In [125]:
# Reshape the price values to a 2D array (required by the scaler)
price_values_2d = price_values.values.reshape(-1, 1)

In [126]:
# Fit and transform the price values using the scaler
normalized_price = scaler.fit_transform(price_values_2d)

In [127]:
# Flatten the normalized price values to a 1D array
normalized_price = normalized_price.flatten()

In [128]:
# Calculate similarity based on price difference
price_difference = np.abs(normalized_price - normalized_price[:, np.newaxis])
price_similarity = 1 - price_difference

In [129]:
price_similarity

array([[1.        , 0.88188976, 0.8976378 , ..., 0.92125984, 0.92125984,
        0.80314961],
       [0.88188976, 1.        , 0.98425197, ..., 0.96062992, 0.96062992,
        0.92125984],
       [0.8976378 , 0.98425197, 1.        , ..., 0.97637795, 0.97637795,
        0.90551181],
       ...,
       [0.92125984, 0.96062992, 0.97637795, ..., 1.        , 1.        ,
        0.88188976],
       [0.92125984, 0.96062992, 0.97637795, ..., 1.        , 1.        ,
        0.88188976],
       [0.80314961, 0.92125984, 0.90551181, ..., 0.88188976, 0.88188976,
        1.        ]])

In [130]:
price_similarity[0]

array([1.        , 0.88188976, 0.8976378 , 0.92125984, 0.87401575,
       0.90551181, 0.96062992, 0.92125984, 0.84251969, 0.86614173,
       0.96062992, 0.86614173, 0.88188976, 0.94488189, 0.81889764,
       0.96062992, 0.96062992, 0.87401575, 0.92125984, 0.90551181,
       0.81889764, 0.80708661, 0.93700787, 0.84251969, 0.85826772,
       0.85826772, 0.90551181, 0.90551181, 0.96062992, 0.87795276,
       0.8503937 , 0.90551181, 0.76377953, 0.95275591, 0.86614173,
       0.96062992, 0.88976378, 0.84251969, 0.93700787, 0.93700787,
       0.96062992, 0.88188976, 0.84251969, 0.78740157, 0.88188976,
       0.79133858, 0.82677165, 0.80314961, 0.88976378, 0.87795276,
       0.7992126 , 0.82677165, 0.7992126 , 0.83464567, 0.85826772,
       0.90551181, 0.81102362, 0.96062992, 0.88976378, 0.84251969,
       0.80314961, 0.88188976, 0.88188976, 0.84251969, 0.76377953,
       0.76377953, 0.60629921, 0.98425197, 0.96062992, 0.96062992,
       0.84251969, 1.        , 0.8976378 , 0.4488189 , 0.89763

In [131]:
price_similarity[92]

array([1.        , 0.88188976, 0.8976378 , 0.92125984, 0.87401575,
       0.90551181, 0.96062992, 0.92125984, 0.84251969, 0.86614173,
       0.96062992, 0.86614173, 0.88188976, 0.94488189, 0.81889764,
       0.96062992, 0.96062992, 0.87401575, 0.92125984, 0.90551181,
       0.81889764, 0.80708661, 0.93700787, 0.84251969, 0.85826772,
       0.85826772, 0.90551181, 0.90551181, 0.96062992, 0.87795276,
       0.8503937 , 0.90551181, 0.76377953, 0.95275591, 0.86614173,
       0.96062992, 0.88976378, 0.84251969, 0.93700787, 0.93700787,
       0.96062992, 0.88188976, 0.84251969, 0.78740157, 0.88188976,
       0.79133858, 0.82677165, 0.80314961, 0.88976378, 0.87795276,
       0.7992126 , 0.82677165, 0.7992126 , 0.83464567, 0.85826772,
       0.90551181, 0.81102362, 0.96062992, 0.88976378, 0.84251969,
       0.80314961, 0.88188976, 0.88188976, 0.84251969, 0.76377953,
       0.76377953, 0.60629921, 0.98425197, 0.96062992, 0.96062992,
       0.84251969, 1.        , 0.8976378 , 0.4488189 , 0.89763

In [132]:
price_similarity[2]

array([0.8976378 , 0.98425197, 1.        , 0.97637795, 0.97637795,
       0.99212598, 0.85826772, 0.81889764, 0.74015748, 0.96850394,
       0.93700787, 0.96850394, 0.98425197, 0.84251969, 0.92125984,
       0.85826772, 0.93700787, 0.97637795, 0.97637795, 0.99212598,
       0.92125984, 0.90944882, 0.96062992, 0.94488189, 0.96062992,
       0.96062992, 0.99212598, 0.99212598, 0.93700787, 0.98031496,
       0.95275591, 0.99212598, 0.66141732, 0.94488189, 0.96850394,
       0.93700787, 0.99212598, 0.74015748, 0.96062992, 0.96062992,
       0.85826772, 0.77952756, 0.74015748, 0.88976378, 0.98425197,
       0.89370079, 0.92913386, 0.90551181, 0.99212598, 0.98031496,
       0.9015748 , 0.92913386, 0.9015748 , 0.93700787, 0.96062992,
       0.99212598, 0.91338583, 0.93700787, 0.99212598, 0.94488189,
       0.90551181, 0.98425197, 0.98425197, 0.94488189, 0.66141732,
       0.66141732, 0.50393701, 0.91338583, 0.85826772, 0.93700787,
       0.94488189, 0.8976378 , 1.        , 0.34645669, 1.     

In [137]:
lat_values = new_df['lat'].values
lng_values = new_df['lng'].values

In [138]:
from math import radians, sin, cos, sqrt, atan2

In [139]:
# Define a function to calculate the Haversine distance
def haversine(lat1, lng1, lat2, lng2):
    # Convert latitude and longitude from degrees to radians
    lat1_rad = np.radians(lat1)
    lng1_rad = np.radians(lng1)
    lat2_rad = np.radians(lat2)
    lng2_rad = np.radians(lng2)

    # Haversine formula
    dlat = lat2_rad - lat1_rad
    dlng = lng2_rad - lng1_rad
    a = np.sin(dlat/2) ** 2 + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(dlng/2) ** 2
    c = 2 * np.arcsin(np.sqrt(a))
    r = 6371  # Radius of the Earth in kilometers
    distance = c * r

    # Similarity based on distance
    similarity = 1 / (1 + distance)

    return similarity

In [140]:
# Calculate the similarity based on distance
distance_similarity = haversine(lat_values[:, np.newaxis], lng_values[np.newaxis, :], lat_values[np.newaxis, :], lng_values[:, np.newaxis])

In [141]:
distance_similarity

array([[1.        , 0.16984057, 0.43758384, ..., 0.12417379, 0.12131434,
        0.19010304],
       [0.16984057, 1.        , 0.13999528, ..., 0.30740798, 0.28918436,
        0.12305932],
       [0.43758384, 0.13999528, 1.        , ..., 0.10720102, 0.10504422,
        0.18218189],
       ...,
       [0.12417379, 0.30740798, 0.10720102, ..., 1.        , 0.82706651,
        0.10400229],
       [0.12131434, 0.28918436, 0.10504422, ..., 0.82706651, 1.        ,
        0.10269106],
       [0.19010304, 0.12305932, 0.18218189, ..., 0.10400229, 0.10269106,
        1.        ]])

In [142]:
distance_similarity[0]

array([1.        , 0.16984057, 0.43758384, 0.28939985, 0.07909774,
       0.31602729, 0.32084834, 0.24215889, 0.34168574, 0.13704146,
       0.66049444, 0.73397707, 0.19226318, 0.32972634, 0.08225952,
       0.14200417, 0.4253622 , 0.09869781, 0.111652  , 0.77075893,
       0.19655269, 0.12797091, 0.30304693, 0.10774514, 0.10569537,
       0.4871216 , 0.10412815, 0.16221909, 0.11990219, 0.10187658,
       0.10563359, 0.60181424, 0.18435891, 0.10335407, 0.09862919,
       0.11022947, 0.0782374 , 0.14285188, 0.08325328, 0.51356724,
       0.20935726, 0.31920106, 0.14426322, 0.09271731, 0.13082063,
       0.12560873, 0.12720266, 0.12605687, 0.11211741, 0.10276842,
       0.12022223, 0.28483034, 0.1276241 , 0.11327036, 0.15807559,
       0.45540105, 0.1338357 , 0.15288874, 0.26631588, 0.11400086,
       0.12518758, 0.11507912, 0.25763505, 0.11825998, 0.09051811,
       0.39149115, 0.14184901, 0.18699071, 0.35565425, 0.63282548,
       0.1195408 , 0.56932202, 0.08640142, 0.20717109, 0.15533

In [143]:
#weight for combined similarity
weight_tags = 0.3
weight_price = 0.3 
weight_distance = 0.4

In [144]:
combined_similarity = (
    weight_tags * similaritytags +
    weight_price * price_similarity +
    weight_distance * distance_similarity
)

In [145]:
combined_similarity

array([[1.        , 0.41500602, 0.57595391, ..., 0.36205467, 0.36091089,
        0.3783016 ],
       [0.41500602, 1.        , 0.45383822, ..., 0.48596973, 0.4319193 ,
        0.44845594],
       [0.57595391, 0.45383822, 1.        , ..., 0.40293803, 0.3796939 ,
        0.43164078],
       ...,
       [0.36205467, 0.48596973, 0.40293803, ..., 1.        , 0.79613273,
        0.4044675 ],
       [0.36091089, 0.4319193 , 0.3796939 , ..., 0.79613273, 1.        ,
        0.35032501],
       [0.3783016 , 0.44845594, 0.43164078, ..., 0.4044675 , 0.35032501,
        1.        ]])

In [146]:
combined_similarity[0]

array([1.        , 0.41500602, 0.57595391, 0.507408  , 0.40030195,
       0.46709131, 0.49737352, 0.49885721, 0.50474219, 0.41317754,
       0.6674315 , 0.66870346, 0.44237312, 0.53437891, 0.33639743,
       0.40850138, 0.54071911, 0.3402334 , 0.40281471, 0.73617287,
       0.35924347, 0.33933225, 0.48909332, 0.32736026, 0.35174121,
       0.53317416, 0.40691398, 0.39595003, 0.4371449 , 0.37140374,
       0.3791475 , 0.5770554 , 0.35498243, 0.37874973, 0.3518047 ,
       0.40951227, 0.37186145, 0.39416314, 0.38673761, 0.64072747,
       0.42526668, 0.48304988, 0.39011941, 0.33094245, 0.39976885,
       0.34705392, 0.36779723, 0.37538443, 0.36218618, 0.37508143,
       0.34033755, 0.43692492, 0.362263  , 0.32197992, 0.38862053,
       0.52196059, 0.33971601, 0.4550633 , 0.40640959, 0.35033899,
       0.34300266, 0.37361118, 0.42135828, 0.34295278, 0.34244021,
       0.52407236, 0.36046253, 0.4815603 , 0.53738661, 0.70335158,
       0.35338675, 0.67625094, 0.40468874, 0.33278421, 0.40343

In [147]:
combined_similarity[0].shape

(100,)

In [148]:
sorted(list(enumerate(combined_similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 0.9999999999999999),
 (19, 0.736172867123587),
 (69, 0.703351577025273),
 (71, 0.6762509389344135),
 (11, 0.6687034551620872),
 (10, 0.6674315012314824),
 (78, 0.6605898743610286),
 (39, 0.6407274739394144),
 (79, 0.6079889771608377),
 (31, 0.5770554041821092),
 (2, 0.5759539093887563),
 (16, 0.5407191127223896),
 (68, 0.5373866101420314),
 (13, 0.5343789081383645),
 (25, 0.5331741631587081),
 (65, 0.5240723583036637),
 (55, 0.521960590755082),
 (75, 0.5078686515121448),
 (3, 0.507407996848394),
 (8, 0.504742186861297),
 (7, 0.49885720973703435),
 (6, 0.49737352051080136),
 (22, 0.48909331829373326),
 (41, 0.483049875216289),
 (67, 0.4815602952871101),
 (92, 0.4777021909911833),
 (5, 0.4670913092759639),
 (89, 0.46037218654605266),
 (57, 0.4550632998542241),
 (12, 0.44237312122096883),
 (28, 0.4371449027427492),
 (51, 0.43692492126428917),
 (93, 0.43256859928053315),
 (40, 0.42526667846735877),
 (62, 0.42135827919026003),
 (90, 0.4177545916896898),
 (1, 0.4150060206282864),
 (9, 0

In [149]:
sorted(list(enumerate(combined_similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(19, 0.736172867123587),
 (69, 0.703351577025273),
 (71, 0.6762509389344135),
 (11, 0.6687034551620872),
 (10, 0.6674315012314824)]

In [156]:
new_df[new_df['_id'] == rooms].index[19]

C:\Users\empsw\AppData\Local\Temp\ipykernel_13108\2904228414.py:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  new_df[new_df['_id'] == rooms].index[19]


19

In [174]:
def recommend(rooms):
    room_index = new_df[new_df['_id'] == rooms].index[0]
    simdistances = combined_similarity[room_index]
    room_list = sorted(list(enumerate(simdistances)), reverse=True, key=lambda x: x[1])[1:5]
    for i in room_list:
        print(new_df.iloc[i[0]]['_id'])

In [175]:
recommend('649704d7cd2d701f93cfbbc5')

6497b5aa20eff54bd37dc88b
6498029e20eff54bd37dcb76
6498061d20eff54bd37dcbd4
6497b0a420eff54bd37dc82a


In [176]:
recommend('6497b5aa20eff54bd37dc88b')

6497b05120eff54bd37dc822
6497b0a420eff54bd37dc82a
649704d7cd2d701f93cfbbc5
6498029e20eff54bd37dcb76


In [177]:
import pickle

In [178]:
pickle.dump(new_df,open('rooms.pkl','wb'))

In [179]:
new_df.to_dict()

{'_id': {0: '649704d7cd2d701f93cfbbc5',
  1: '6497061ccd2d701f93cfbbcf',
  2: '64970670cd2d701f93cfbbd7',
  3: '64970739cd2d701f93cfbbe8',
  4: '64970881cd2d701f93cfbbf0',
  5: '64970b7ccd2d701f93cfbbf8',
  6: '64970d5dcd2d701f93cfbc09',
  7: '64970ea4cd2d701f93cfbc15',
  8: '64970f71cd2d701f93cfbc1d',
  9: '6497affa20eff54bd37dc819',
  10: '6497b05120eff54bd37dc822',
  11: '6497b0a420eff54bd37dc82a',
  12: '6497b18520eff54bd37dc83b',
  13: '6497b1d720eff54bd37dc843',
  14: '6497b25820eff54bd37dc84b',
  15: '6497b34a20eff54bd37dc862',
  16: '6497b3df20eff54bd37dc86a',
  17: '6497b43220eff54bd37dc872',
  18: '6497b55d20eff54bd37dc883',
  19: '6497b5aa20eff54bd37dc88b',
  20: '6497b5ff20eff54bd37dc893',
  21: '6497ceb820eff54bd37dc8ae',
  22: '6497cf1520eff54bd37dc8ba',
  23: '6497cf7520eff54bd37dc8c2',
  24: '6497d04820eff54bd37dc8da',
  25: '6497d0c120eff54bd37dc905',
  26: '6497d12a20eff54bd37dc913',
  27: '6497d19f20eff54bd37dc91b',
  28: '6497d26020eff54bd37dc92b',
  29: '6497d2df20

In [180]:
pickle.dump(new_df.to_dict(),open('room_dict.pkl','wb'))

In [181]:
pickle.dump(combined_similarity,open('similarity.pkl','wb'))